## Ejercicios - Algebra

In [1]:
import numpy as np

import random

In [2]:
# Versiones
print(f"numpy=={np.__version__}")

numpy==2.2.0


### Ejercicio 1:
- Usando la librería _**random**_, genera una matriz de $4x4$ de números enteros del 1 al 100, usando bucles.
- El resultado debe ser un _**np.array()**_.

In [3]:
matriz = np.array([[1, 2, 3], [1, 2, 3]])
print(matriz)
print(matriz.shape)  #primero da las filas y luego las columnas

[[1 2 3]
 [1 2 3]]
(2, 3)


In [4]:
# en el ejercicio se pide 4x4


In [5]:
matriz = np.array([[1, 2, 3], [1, 2, 3]])
print(matriz)
print(matriz.shape)  #primero da las filas y luego las columnas
# Uso de bucles for para crear una lista en Python y pasarla a array de numpy

[[1 2 3]
 [1 2 3]]
(2, 3)


In [6]:
matriz = list()
import numpy as np
import random

for i in range(4):
    fila = list()
    
    for j in range(4):
        # numero_aleatorio = 1  para descomponer el problema en partes y ver si funciona
        # numero_aleatorio = j       
        numero_aleatorio = random.randint(1, 100)
        fila.append(numero_aleatorio)
        
    matriz.append(fila)
     
print(matriz)    
np.array(matriz)


[[8, 97, 35, 27], [67, 100, 8, 97], [5, 43, 32, 27], [1, 14, 97, 51]]


array([[  8,  97,  35,  27],
       [ 67, 100,   8,  97],
       [  5,  43,  32,  27],
       [  1,  14,  97,  51]])

In [7]:
# matriz = list()
import numpy as np
import random

matriz = []
for i in range(4):
    fila = []
    
    for j in range(4):
        # numero_aleatorio = i
        # numero_aleatorio = j
        numero_aleatorio = random.randint(1, 100)
        fila.append(numero_aleatorio)
    
    matriz.append(fila)
    
np.array(matriz)

array([[99, 81, 68, 82],
       [72, 79, 95, 53],
       [89, 70, 74, 43],
       [96, 64, 76, 41]])

In [8]:
#se puede poner comprimido:
np.array([[random.randint(1, 100) for j in range(4)] for i in range(4)])

array([[ 66,  53,  93,  88],
       [ 71,  61,  70,  29],
       [ 50, 100,  42,  77],
       [ 78,  21,  28,  20]])

### Ejercicio 2:

- Define una función que tome como parámetro de entrada 2 valores enteros ($m$, $n$).
- La función debe generar, usando la librería _**random**_, una matriz de $mxn$ de números enteros del 1 al 100, usando bucles.
- La función debe retornar la matriz, la matriz debe ser un _**np.array()**_.

In [9]:
matriz = np.array([[1, 2, 3], [1, 2, 3]])
print(matriz)
print(matriz.shape) # se pide (m, n)
# Uso de bucles for para crear una lista en python y pasarla a array de numpy

[[1 2 3]
 [1 2 3]]
(2, 3)


In [10]:
# en este caso es una matriz dinamica, de mxn
# hay que crear una función
def generar_matriz(m=4, n=4): # añadiendo un valor nos aseguramos que al menos tendrá estas dimensiones si se introducen m y n mal
    matriz = []
    if m<=0 or n<=0:
        raise ValueError("Dimensiones incorrectas")
    
    for i in range(m):
        fila = []
        for j in range(n):
            numero_aleatorio = random.randint(1, 100)
            fila.append(numero_aleatorio)
        
        matriz.append(fila)
    return np.array(matriz)

generar_matriz(4, 6)


array([[78, 20, 76, 66, 81, 23],
       [10, 46, 45, 60, 76, 52],
       [62, 48, 13, 93, 64, 77],
       [ 2, 79, 89, 57, 60,  8]])

In [12]:
def generar_matriz(m=4, n=4):
    matriz = []
    if m <= 0 or n <= 0:
        raise ValueError("Dimensiones incorrectas")
        #print("las dimensiones deben ser mayor de 0.")
        
    for i in range(m):
        fila = []
        for j in range(n):
            numero_aleatorio = random.randint(1, 100)
            fila.append(numero_aleatorio)
        
        matriz.append(fila)
    return np.array(matriz)
    
generar_matriz(1, 4)

array([[ 7, 31, 39,  8]])

In [11]:
##############################################################################################################################