<a href="https://colab.research.google.com/github/CaroliCosas/Bootcamp_Data_Science/blob/main/01_numpy_1_ejercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ejercicios - NumPy 1

In [16]:
import numpy as np

In [2]:
# Versión
print(f"numpy=={np.__version__}")

numpy==1.26.4


### Ejercicio 1:
- Crea un vector con 10 elementos pares.

In [3]:
lista = []
for i in range(20):
    if i % 2 == 0:
        lista.append(i)

np.array(lista)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
lista = []
for i in range(2, 22, 2):
    lista.append(i)

np.array(lista)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
array_pares = np.array([i for i in range(2, 22, 2)])
array_pares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Ejercicio 2:
- Obten el número de dimensiones y el tamaño del vector anterior.

In [6]:
array_pares.ndim

1

In [7]:
# numero de elementos en total
array_pares.size

10

In [8]:
# numero de elementos en cada dimension
array_pares.shape

(10,)

In [9]:
array_pares.dtype

dtype('int64')

In [10]:
array = np.array([10, 10, 20, 20, 30, 30])
array

array([10, 10, 20, 20, 30, 30])

In [11]:
array_acumulado = np.cumsum(array)
array_acumulado

array([ 10,  20,  40,  60,  90, 120])

In [12]:
np.diff(array_acumulado)

array([10, 20, 20, 30, 30])

In [13]:
# agregar el primero manualmente ya que no tiene ninguno delante para obtener el diff
original = np.insert(np.diff(array_acumulado), 0, array_acumulado[0])
original

array([10, 10, 20, 20, 30, 30])

### Ejercicio 3:
- Crea una lista con 5 números pares y otra lista con 5 números impares utilizando **list comprehension** y conviertelos en una matriz de (5, 2) dimensiones.

In [18]:
pares = np.array([i for i in range(2,11,2)])
pares

# concatenate y reshape

array([ 2,  4,  6,  8, 10])

In [25]:
impares = np.array([i for i in range(1,11,2)])
impares

array([1, 3, 5, 7, 9])

In [27]:
numbers = np.concatenate((pares, impares))
numbers

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [28]:
print(pares)
print(np.where(pares > 5))

[ 2  4  6  8 10]
(array([2, 3, 4]),)


In [29]:
indices = np.where(pares > 5)
pares[indices]

array([ 6,  8, 10])

Está devolviendo los índices, que luego me pueden interesar


### Ejercicio 4:
- Obten el tipo de datos de la matriz anterior.

In [17]:
matriz_5x2.dtype

NameError: name 'matriz_5x2' is not defined

In [ ]:
matriz_5x2.flatten()

In [14]:
np.ravel(matriz_5x2)

In [14]:
np.column_stack(matriz_5x2)

### Ejercicio 5:
- Crea una matriz de ceros de dimensión (4, 4) y remplaza los elementos de la diagonal principal por los números 5.

### Ejercicio 6:
- Utiliza la función _**np.linspace()**_ para crear un vector con 10 elementos entre los números: -5 y 5.

### Ejercicio 7:
- Crea una matriz vacía de tamaño (3, 6) con elementos del tipo flotante.

### Ejercicio 8:
- Utiliza la matriz anterior para llenarla con números primos (investiga en internet una función que genere números primos e implementala).

### Ejercicio 9:
- Reemplaza los números de color azul por un 99 utilizando slicing.

$$\Large
\begin{bmatrix}
 1 &  2 &  \color{Blue}{3} &  4 \\
 5 &  \color{Blue}{6} &  7 &  \color{Blue}{8} \\
 \color{Blue}{9} & 10 & 11 & 12 \\
13 & 14 & \color{Blue}{15} & 16
\end{bmatrix}
$$

### Ejercicio 10:
- Obten la primera y tercera fila de la matriz.

### Ejercico 11:
- Obten la tercera columna de la matriz.

### Ejercicio 12:
- Obtener la segunda y tercera columna de la matriz.

### Ejercicio 13:
- Obten una submatriz con los 4 números del centro.

### Ejercicio 14:
- Aplica la función _**np.flatten()**_ a la matriz anterior para obtener un vector.

### Ejercicio 15:
- Aplica el método _**.reshape()**_ al vector anterior para obtener una matriz de (1, 4) dimensiones.

### Ejercicio 16:
- Crea dos matrices de dimensión (4, 4) con números aleatorios y concatenalas verticalmente.

In [15]:
################################################################################################################################